### PR TITLE
Fixes wimglenn/oyaml#15

### PR DESCRIPTION
**Pull request by wolfgang-noichl**
See the aforementioned issue for discussion.

### CODE REVIEW

**Comment by wolfgang-noichl** [comment]
Does not seem to work yet, but the idea is to monkey patch only a "copy" of the yaml module.

**Comment by wimglenn** [comment]
This creates exception types which have different identities.

```
>>> import oyaml.representer
>>> import yaml.representer
>>> yaml.representer.RepresenterError is oyaml.representer.RepresenterError
False
```

That has bad consequences for try/except blocks, which I think is the cause of the test failures.

**Comment by wimglenn** [comment]
Closing, because the cure is worse than the disease. See #15 for some discussion.

**Comment by wimglenn** [comment]
Closing, because the cure is worse than the disease. See #15 for additional discussion.

**Pull request closed without merging**
